## code to prepare `lipid_classes` dataset goes here

lipid_classes <- c(
  "PC", "aPC", "ePC",
  "LPC",
  "PE", "aPE", "ePE",
  "LPE",
  "plPE16-0", "PE P-16-0", "PE P-16_0",
  "plPE18-1", "PE P-18-1", "PE P-18_1",
  "plPE18-0", "PE P-18-0", "PE P-18_0",
  "PS", "aPS", "ePS",
  "LPS",
  "PI", "aPI", "ePI",
  "LPI",
  "PG", "aPG", "ePG",
  "LPG",
  "PA", "aPA", "ePA",
  "LPA",
  "CL",
  "MLCL",
  "SM",
  "Cer",
  "tCer",
  "HexCer", "GlcCer",
  "Hex2Cer", "LacCer",
  "Hex3Cer",
  "GM3", "GM2", "GM1",
  "EE",
  "SAA", "Ergo",
  "CA", "Chol",
  "CE",
  "MAG", "MG",
  "DAG", "DG",
  "TAG", "TG")

usethis::use_data(lipid_classes, overwrite = TRUE)
